### Register User
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "test3@gmail.com",
    "password": "password",
    "name": "test",
    "role": "user",
    "dob": "01-01-1999",
    "gender": "male",
    "issue": ["Stuttering", "Voice Disorder"]
}

### Register Therapist
POST http://localhost:3001/auth/register-superuser
Content-Type: application/json

{
    "email": "testsuperuser2@gmail.com",
    "password": "password",
    "name": "testsuperuser2",
    "role": "therapist",
    "purpose": ["treatment"],
    "organisation": "SIT"
}

### Register Admin
POST http://localhost:3001/auth/register-admin
Content-Type: application/json

{
    "email": "testadmin@gmail.com",
    "password": "password",
    "name": "testadmin"
}

### Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "zemuskoh99@gmail.com",
    "password": "Password1"
}

### Forgot Password
POST http://localhost:3001/auth/forgot-password
Content-Type: application/json

{
    "email": "zemuskoh99@gmail.com"
}

### Reset Password
POST http://localhost:3001/auth/reset-password 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzRjYjY3NGU5YWVjNzdlYmY1MTk5MyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg2ODIyNzkzfQ.vG3IM3rdqbIetHAMuvKz_8qzuYIyjMJjalrblOLvPZs",
    "password": "password1",
    "newPassword": "password0"
}


### Get Role
GET http://localhost:3001/auth/role/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGFjZjZjYWMwMjhkMTAzNTA3MTI0MiIsInJvbGUiOiJ0aGVyYXBpc3QiLCJpYXQiOjE2ODgyMDYzOTV9.7-4zgwZYuXdrEPWUPyM-Yf-AgkO33uFo_nzlGivLKC8



