POST

// admin
{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "hashedPassword",
    "role": "admin"
}

// superusers
{
    "name": "superuser",
    "email": "superuser@gmail.com",
    "password": "hashedPassword",
    "role": "therapist",
    "purpose": [
        "treatment",
         "education"
    ],
    "organisation": "SIT"
}

// users
{
    "name": "user",
    "email": "user@gmail.com",
    "password": "hashedPassword",
    "role": "user",
    "dob": 1998-12-31T16:00:00.000+00:00,
    "gender": "male",
    "issue" : [
        "Stuttering", 
        "Voice Disorder", 
        "Stroke Recovery"
    ],
    "therapist": "therapist@gmail.com"
}

// scenarios
{
    "category": "Food",
    "scenario": "Fast Food",
    "videos": [
        {"videoName": "Fast Food 1", "videoId": "kJQP7kiw5Fk"},
        {"videoName": "Fast Food 2", "videoId": "kJQP7kiw5Fk"},
        {"videoName": "Fast Food 3", "videoId": "kJQP7kiw5Fk"},
    ],
    "dateAdded": 2022-12-31T16:00:00.000+00:00,
}



// tasks
{
    "therapist": "therapist@gmail.com",
    "patient": "patient@gmail.com",
    "dateAssigned": 2022-12-31T16:00:00.000+00:00,
    "category": "Food",
    "scenario": "Fast Food",
    "videoIds": ["kJQP7kiw5Fk", "kJQP7kiw5Fk", "kJQP7kiw5Fk"],
    "submission": [
        {"title": "Fast Food 1", 
        "recodingLink": "test", 
        "patientStutter": 5, 
        "patientFluency": 5, 
        "patientRemark": "remark",
        "therapistStutter": 5, 
        "therapistFluency": 5, 
        "therapistRemark": "remark",
        "dateSubmitted": 2022-12-31T16:00:00.000+00:00}
    ],
    "status": "Completed"
}
