POST http://localhost:3001/tasks/create-temp
Content-Type: application/json

{
    "category": "testCat",
    "scenario": "testSce3",
    "videoName": "testName",
    "videoId": "testVidId3",
    "dateAdded": "01-01-1999"
}

###
GET http://localhost:3001/tasks/scenarios