### Get profile details
GET http://localhost:3001/users/profile/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM5MWY0ODJhNWU2NzAxZjM4NTMyZiIsInJvbGUiOiJ0aGVyYXBpc3QiLCJpYXQiOjE2ODY1ODE2NTh9.rg2QQWmu2s8KKQA0cMdvyomByIjZibB4B5DUjTmoNyU

### Edit profile details
POST http://localhost:3001/users/edit-profile
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM5MWY0ODJhNWU2NzAxZjM4NTMyZiIsInJvbGUiOiJ0aGVyYXBpc3QiLCJpYXQiOjE2ODY1ODE2NTh9.rg2QQWmu2s8KKQA0cMdvyomByIjZibB4B5DUjTmoNyU",
    "fields": {"name": "therapist2", "organisation": "SIT"}
}

### Add API Key (therapist)
POST http://localhost:3001/users/add-api-key
Content-Type: application/json

{
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM5MWY0ODJhNWU2NzAxZjM4NTMyZiIsInJvbGUiOiJ0aGVyYXBpc3QiLCJpYXQiOjE2ODY1ODE2NTh9.rg2QQWmu2s8KKQA0cMdvyomByIjZibB4B5DUjTmoNyU",
        "apiKey": "test"
}

### Get therapist names and email
GET http://localhost:3001/users/therapists

### Get all therapists
POST http://localhost:3001/users/therapists
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGFjZjYwYWMwMjhkMTAzNTA3MTIzZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjgyNzg0NH0.L1T2vpBRGP38e_3PHa6x6pH9_-d75Gi5aeU9C6j2VWI"
}

### Get patient

